# Generated by Django 3.0.3 on 2020-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Email', models.CharField(max_length=50)),
                ('Comment', models.CharField(max_length=1000)),
            ],
        ),
    ]
