# Generated by Django 3.0.8 on 2020-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Archived',
            field=models.BooleanField(default=False),
        ),
    ]
