# Generated by Django 3.0.8 on 2020-07-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20200721_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information_slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('latest_news', models.CharField(max_length=255)),
            ],
        ),
    ]
